#!/usr/bin/env bash
# Auto-generated by scaffold_research_project.py — F-C INFRASTRUCTURE_INDEX.md regeneration shim.
# Reference-by-shim; invokes ~/ml-governance-templates/scripts/gen_infrastructure_index.py.
set -euo pipefail
PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
python3 "$HOME/ml-governance-templates/scripts/gen_infrastructure_index.py" --project "$PROJECT_DIR"
