#!/usr/bin/env bash
# Auto-generated by scaffold_research_project.py — F-A structural-rail invocation shim.
# Reference-by-shim per reproduce.sh L583 convention; NO body duplication of govML scripts.
#
# Usage: bash scripts/run_gates.sh [stage]
#   No arg = run all applicable gates for this project's research_type.
set -euo pipefail
PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
GOVML="$HOME/ml-governance-templates/scripts"

echo "=== Running govML gates for $(basename "$PROJECT_DIR") ==="
echo ""

# Pre-compute check (precondition gate; Stage 5 entry)
if [ -x "$GOVML/pre_compute_check.sh" ]; then
    echo "--- pre_compute_check.sh ---"
    bash "$GOVML/pre_compute_check.sh" "$PROJECT_DIR" || echo "  (exit $? — see verdict above)"
    echo ""
fi

# Landscape depth gate F3 (Stage 2 → Stage 3 transition; F3 hybrid composite per parent cycle)
if [ -x "$GOVML/landscape_depth_gate_F3.sh" ] && [ -f "$PROJECT_DIR/LANDSCAPE_ASSESSMENT.md" ]; then
    echo "--- landscape_depth_gate_F3.sh ---"
    bash "$GOVML/landscape_depth_gate_F3.sh" "$PROJECT_DIR/LANDSCAPE_ASSESSMENT.md" || echo "  (exit $? — see verdict above)"
    echo ""
fi

# All gates (post-Phase-1 + Phase 3 readiness)
if [ -x "$GOVML/check_all_gates.sh" ]; then
    echo "--- check_all_gates.sh ---"
    bash "$GOVML/check_all_gates.sh" "$PROJECT_DIR" || echo "  (exit $? — see verdict above)"
    echo ""
fi

echo "=== Gates complete ==="
