#!/usr/bin/env bash
# Auto-generated by scaffold_research_project.py — Cycle-14-S9 Builder ARCH back-port.
# Reference-by-shim per BUILD_DECISION_LOG §7.4 architectural choice (b): invokes
# the 5 Cycle 14 patched rubrics at govML canonical location. NO body duplication.
#
# Usage: bash scripts/run_build_rubrics.sh [rubric_name | --list]
#   --list        = list available rubric names
#   <rubric_name> = run a specific rubric (be1_m3 / be2_m3_m4 / be3_m1_m4 / be4_m4 / be5_m2_m4)
#   (no arg)      = run all 5 against current project's build/ artifacts
set -euo pipefail
PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
GOVML_RUBRICS="$HOME/ml-governance-templates/scripts/build_rubrics"

if [ ! -d "$GOVML_RUBRICS" ]; then
    echo "ERROR: govML build_rubrics not found at $GOVML_RUBRICS" >&2
    echo "       Install: git clone https://github.com/rexcoleman/govML.git \$HOME/ml-governance-templates" >&2
    exit 1
fi

RUBRICS=(
    "be1_m3_traceability_check_cycle_14_patched.py"
    "be2_m3_m4_test_spec_coverage_check_cycle_14_patched.py"
    "be3_m1_m4_live_vs_mock_check_cycle_14_patched.py"
    "be4_m4_mutation_survival_check_cycle_14_patched.py"
    "be5_m2_m4_agent_resilience_check_cycle_14_patched.py"
)

if [ "${1:-}" = "--list" ]; then
    echo "Cycle 14 patched build-class rubrics (at $GOVML_RUBRICS):"
    for r in "${RUBRICS[@]}"; do echo "  $r"; done
    exit 0
fi

echo "=== Running Cycle 14 patched build-class rubrics for $(basename "$PROJECT_DIR") ==="
echo "=== govML canonical location: $GOVML_RUBRICS ==="
echo ""

if [ -n "${1:-}" ]; then
    # Run a specific rubric (prefix match against the 5 rubric stems)
    for r in "${RUBRICS[@]}"; do
        if [[ "$r" == "$1"* ]] || [[ "$r" == *"$1"* ]]; then
            echo "--- $r ---"
            python3 "$GOVML_RUBRICS/$r" "$PROJECT_DIR" || echo "  (exit $? — see verdict above)"
            exit 0
        fi
    done
    echo "ERROR: no rubric matched '$1'. Use --list to see options." >&2
    exit 1
fi

# Run all 5
for r in "${RUBRICS[@]}"; do
    echo "--- $r ---"
    python3 "$GOVML_RUBRICS/$r" "$PROJECT_DIR" || echo "  (exit $? — see verdict above)"
    echo ""
done

echo "=== Build-class rubrics complete ==="
